"""
Django settings for learnhub project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import os
from pathlib import Path
from django.conf import settings
from django.contrib.auth import login

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY WARNING: don't run with debug turned on in production!

# SECRET_KEY = 'django-insecure-7s+quyy2dcuawnmdd%z-vzbgr_!8ti3zm2bcx4#ekn68jaemw9'

SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-7s+quyy2dcuawnmdd%z-vzbgr_!8ti3zm2bcx4#ekn68jaemw9')
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '*').split(",")
ADMIN_PAGE = os.getenv('ADMIN_PAGE' , 'admin') + "/"
DEBUG = os.getenv('DEBUG', 'True') == 'True'

#bool(int(os.getenv('DEBUG', 1)))

#DEBUG = not True
# ALLOWED_HOSTS = ['*']
# ALLOWED_HOSTS = ['yourdomain.com', 'www.yourdomain.com']
# ALLOWED_HOSTS = ['*.yourdomain.com']
# ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core.apps.CoreConfig',
    'accounts.apps.AccountsConfig',
    'courses.apps.CoursesConfig',
    # 'social.apps.SocialConfig',
    # 'radio.apps.SocialConfig',
    'import_export',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'accounts.middlewares.UpdateLastActivityMiddleware',
    'django.middleware.locale.LocaleMiddleware',
]

ROOT_URLCONF = 'learnhub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'learnhub.context_processors.card_shadow',
            ],
        },
    },
]

WSGI_APPLICATION = 'learnhub.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'database/db.sqlite3',
#     }
# }

DATABASE_PATH = os.getenv('DATABASE_PATH', BASE_DIR / 'database/db.sqlite3')
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DATABASE_PATH,
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'
# LANGUAGE_CODE = 'fa'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'

if DEBUG:
    STATICFILES_DIRS = [
        BASE_DIR / 'core/static',
    ]
    MEDIA_ROOT = BASE_DIR / 'media'
else:
    STATIC_ROOT = '/app/static'
    MEDIA_ROOT = '/app/media'

# STATICFILES_DIRS = [
#     BASE_DIR / 'core/static',
# ]
#
# STATIC_URL = '/static/'
# STATIC_ROOT = os.path.join(BASE_DIR, "static")
# # STATIC_ROOT = './static'
#
# MEDIA_URL = '/media/'
# MEDIA_ROOT = os.path.join(BASE_DIR, "media")
# # MEDIA_ROOT = './media'

LOGIN_URL='/accounts/auth-login.html'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

COURSE_DESCRIPTION = 'این دوره آموزش برای کسانی طراحی شده است که به دنبال یادگیری هستند و به صورت گام به گام به شما کمک خواهد کرد تا (مهارت خاص یا هدف آموزش) را به دست آورید.'
LESSON_DESCRIPTION = 'در طول این ویدیو، قدم به قدم با شما خواهیم بود تا مفاهیم به سادگی و قابل فهم برای شما ارائه شوند. در نهایت، شما قادر خواهید بود تا (نتیجه یا مهارت موردنظر) را به خوبی اجرا کنید.'
SITE_DEFAULT_ICON = f'assets/images/default/default-icon-sm.png'
SITE_DEFAULT_LOGO = f'assets/images/default/default-logo.png'


SITE_WEBSITE = 'https://github.com/mojtabco/learnhub'
TIME_MINUTES_AGO = 5
CARD_SHADOW ='shadow'
VERSION_SITE = '1.2583H9'

COURSE_EVERYONE = 'Everyone'

USER_ALL_ACCESS = 'All-Access'
USER_DELETE = 'Delete'
USER_DOWNLOAD = 'Download'
USER_UPLOAD = 'Upload'
USER_COURSE_ACCESS = 'Course-Access'



